### ISSUE TITLE
Crashing issues with latest versions of praw

### ISSUE THREAD

**Issue by blixnood** [vindimy/altcointip#43]
Bot keeps crashing at random intervals with this error:

```
ERROR 2015-08-12 20:53:12,255 CointipBot::check_inbox(): 
ERROR 2015-08-12 20:53:12,263 CointipBot::main(): exception: 
ERROR 2015-08-12 20:53:12,307 CointipBot::main(): traceback: Traceback (most recent call last):
  File "cointipbot.py", line 558, in main
    self.check_inbox()
  File "cointipbot.py", line 195, in check_inbox
    messages = list(ctb_misc.praw_call(self.reddit.get_unread, limit=self.conf.reddit.scan.batch_limit))
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 524, in get_content
    page_data = self.request_json(url, params=params)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 173, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 579, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 424, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 203, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
HTTPException
```

```
ERROR 2015-08-21 06:00:20,182 CointipBot::check_inbox(): 
ERROR 2015-08-21 06:00:20,182 CointipBot::main(): exception: 
ERROR 2015-08-21 06:00:20,326 CointipBot::main(): traceback: Traceback (most recent call last):
  File "cointipbot.py", line 558, in main
    self.check_inbox()
  File "cointipbot.py", line 195, in check_inbox
    messages = list(ctb_misc.praw_call(self.reddit.get_unread, limit=self.conf.reddit.scan.batch_limit))
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 549, in get_content
    page_data = self.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 604, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 437, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 207, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
HTTPException
```

This one is different:

```
ERROR 2015-08-23 05:08:58,386 CointipBot::check_inbox(): 
ERROR 2015-08-23 05:08:58,386 CointipBot::main(): exception: 
ERROR 2015-08-23 05:08:58,433 CointipBot::main(): traceback: Traceback (most recent call last):
  File "cointipbot.py", line 558, in main
    self.check_inbox()
  File "cointipbot.py", line 241, in check_inbox
    action.do()
  File "ctb/ctb_action.py", line 310, in do
    ctb_stats.update_user_stats(ctb=self.ctb, username=self.u_from.name)
  File "ctb/ctb_stats.py", line 215, in update_user_stats
    res = ctb_misc.praw_call(r.set_flair, username, flair, '')
  File "ctb/ctb_misc.py", line 38, in praw_call
    res = prawFunc(*extraArgs, **extraKwArgs)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 57, in wrapped
    return function(self.reddit_session, self, *args, **kwargs)
  File "<string>", line 2, in set_flair
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 245, in wrap
    if mod and not _is_mod_of_all(obj.user, subreddit):
  File "/usr/local/lib/python2.7/dist-packages/praw/decorator_helpers.py", line 23, in _is_mod_of_all
    mod_subs = user.get_cached_moderated_reddits()
  File "/usr/local/lib/python2.7/dist-packages/praw/objects.py", line 962, in get_cached_moderated_reddits
    for sub in self.reddit_session.get_my_moderation(limit=None):
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 549, in get_content
    page_data = self.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 123, in raise_api_exceptions
    raise exc
HTTPException
```

```
ERROR 2015-08-24 02:42:59,019 CointipBot::check_inbox(): 
ERROR 2015-08-24 02:42:59,019 CointipBot::main(): exception: 
ERROR 2015-08-24 02:42:59,041 CointipBot::main(): traceback: Traceback (most recent call last):
  File "cointipbot.py", line 558, in main
    self.check_inbox()
  File "cointipbot.py", line 195, in check_inbox
    messages = list(ctb_misc.praw_call(self.reddit.get_unread, limit=self.conf.reddit.scan.batch_limit))
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 549, in get_content
    page_data = self.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 604, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 437, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 207, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)
HTTPException
```

**Comment by doged** [comment]
@blixnood having same issue, but crash is different:

dude@ubuntu:~/reddittipbot/src# ./_start.sh
INFO:cointipbot:CointipBot::init_logging(): -------------------- logging initialized --------------------
DEBUG:cointipbot:CointipBot::connect_db(): connecting to database...
INFO:cointipbot:CointipBot::connect_db(): connected to database xxx 
DEBUG:cointipbot:CtbCoin::__init__(): connecting to DogecoinDark...
DEBUG:bitcoin:Read 8 parameters from ~/.DogeCoinDark/DogeCoinDark.conf
DEBUG:bitcoin:Making HTTP connection to 127.0.0.1:8332
INFO:cointipbot:CtbCoin::__init__():: connected to DogecoinDark
INFO:cointipbot:Setting tx fee of 1.000000
DEBUG:bitcoin:Starting "settxfee" JSON-RPC request
DEBUG:bitcoin:Got 36 byte response from server in 4 ms
DEBUG:cointipbot:CtbExchange::__init__(): initialized exchange pubapi.cryptsy.com
DEBUG:cointipbot:CointipBot::connect_reddit(): connecting to Reddit...
Version 2.1.19 of praw is outdated. Version 3.2.1 was released Wednesday August 19, 2015.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cointipbot.py", line 521, in __init__
    self.reddit = self.connect_reddit()
  File "cointipbot.py", line 125, in connect_reddit
    conn.login(self.conf.reddit.auth.user, self.conf.reddit.auth.password)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 1266, in login
    self.user = self.get_redditor(user)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 890, in get_redditor
    return objects.Redditor(self, user_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/objects.py", line 663, in __init__
    fetch, info_url)
  File "/usr/local/lib/python2.7/dist-packages/praw/objects.py", line 72, in __init__
    self.has_fetched = self._populate(json_dict, fetch)
  File "/usr/local/lib/python2.7/dist-packages/praw/objects.py", line 127, in _populate
    json_dict = self._get_json_dict() if fetch else {}
  File "/usr/local/lib/python2.7/dist-packages/praw/objects.py", line 120, in _get_json_dict
    as_objects=False)
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 161, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 526, in request_json
    data = json.loads(response, object_hook=hook)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by doged** [comment]
was working fine until a week or two ago.. just noticed this earlier today..

**Comment by evan4498** [comment]
FYI We are seeing the same thing...

Traceback (most recent call last):
  File "bot.py", line 63, in <module>
    x = RedditBot()
  File "bot.py", line 36, in __init__
    self.check_loop()
  File "bot.py", line 42, in check_loop
    for comment in self.r.get_comments('maddenultimateteam', limit=50):
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 549, in get_content
    page_data = self.request_json(url, params=params)
  File "<string>", line 2, in request_json
  File "/usr/local/lib/python2.7/dist-packages/praw/decorators.py", line 113, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 604, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python2.7/dist-packages/praw/__init__.py", line 437, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python2.7/dist-packages/praw/internal.py", line 207, in _raise_response_exceptions
    raise HTTPException(_raw=exc.response)

**Comment by vindimy** [comment]
Merge #45 should address this.
